final_answer = rag_query(new_prompt, show_sources=True)
print("Final Answer from Qwen:")
print(final_answer)

#Final Task
#Subtask:
#Present the final answer generated by Qwen, which will now include the accurate unemployment rate for the United States in 2019.

#Summary:
#Q&A
#The unemployment rate in the United States in 2019 was 3.7%.

#Data Analysis Key Findings
#The unemployment rate for the United States in 2019 was programmatically extracted from the provided data as 3.7%.
#A new prompt was constructed for Qwen, explicitly stating "The unemployment rate in the United States in 2019 is 3.7% based on the provided data." and asking Qwen to use this value.
#Qwen successfully processed the crafted prompt and provided a concise answer: "The unemployment rate in the United States in 2019 was 3.7%." This demonstrates that the model accurately incorporated the specified numerical value.
#Insights or Next Steps
#This method effectively ensures that Large Language Models (LLMs) provide precise, fact-based answers by programmatically injecting verified numerical data into the prompt, preventing hallucinations or reliance on outdated information.
#Future applications could extend this approach to automate the extraction and integration of various dynamic data points into LLM queries for consistent accuracy across different domains.
#Task
#Modify the existing code to create a generalized function called get_factor_value_answer. This function will take country, year, and factor_name as parameters. It will use pandas to extract the specified factor_name for the given country and year from the loaded CSV data. It will then construct a dynamic prompt for Qwen, including the extracted factual value. Finally, it will call rag_query with this prompt and return Qwen's answer. Demonstrate the usage of this new function by calling it to get the 'Unemployment rates' for 'United States' in '2019' and 'Tourist Expenditure (USD)' for 'Australia' in '2018', and print the results.

#Modify get_unemployment_rate_answer to get_factor_value_answer
#Subtask:
#Rename the existing get_unemployment_rate_answer function to get_factor_value_answer. This new function will accept an additional parameter factor_name (e.g., 'Unemployment rates', 'Tourist Expenditure (USD)') to generalize its functionality. The internal logic will be updated to extract the specified factor_name using pandas and construct a dynamic prompt for Qwen.

#Reasoning: The subtask requires defining a new function get_factor_value_answer that generalizes the logic for extracting specific data points from the CSV and constructing a dynamic prompt for Qwen. This command creates that function.



import pandas as pd
import io

def get_factor_value_answer(country: str, year: int, factor_name: str) -> str:
    """Extracts a specific factor value for a given country and year and queries Qwen with it."""
    # 1. Read the CSV data from the global 'documents' list into a pandas DataFrame
    csv_data = documents[0]
    df_context = pd.read_csv(io.StringIO(csv_data))

    # 2. Filter for the specified country and year
    filtered_df = df_context[(df_context['Country'] == country) & (df_context['Year'] == year)]

    # 3. Extract the factor_name value
    extracted_value = "N/A"
    if not filtered_df.empty:
        # Check if the factor_name column exists and handle potential errors
        if factor_name in filtered_df.columns:
            extracted_value = filtered_df[factor_name].iloc[0]
            print(f"Programmatically extracted {factor_name} for {country} in {year}: {extracted_value}")
        else:
            print(f"Warning: Factor '{factor_name}' not found in the data.")
    else:
        print(f"Data not found for {country} in {year}.")

    # 4. Construct a dynamic prompt for Qwen
    new_prompt = f"""You are a helpful assistant.\n\nHere is a factual statement: The {factor_name} in {country} in {year} is {extracted_value} based on the provided data.\n\nQuestion: What was the {factor_name} in {country} in {year}?\n\nBased on the factual statement provided, what was the {factor_name} in {country} in {year}? Provide a concise answer using the given numerical value.\n\nAnswer:\n"""

    print("Generated new Qwen prompt with explicit value:")
    print(new_prompt)

    # 5. Call rag_query with the newly constructed prompt
    final_answer = rag_query(new_prompt, show_sources=False)

    return final_answer

print("Function 'get_factor_value_answer' defined.")

#Reasoning: Now that the get_factor_value_answer function is defined, I will call it twice as requested in the subtask: once for 'Unemployment rates' in 'United States' for '2019' and once for 'Tourist Expenditure (USD)' in 'Australia' for '2018', and then print the results.

print("Querying for Unemployment rate in United States in 2019...")
unemployment_result = get_factor_value_answer("United States", 2019, "Unemployment rates")
print(f"Result for Unemployment rate in United States (2019):\n{unemployment_result}\n")

print("Querying for Tourist Expenditure (USD) in Australia in 2018...")
tourist_expenditure_result = get_factor_value_answer("Australia", 2018, "Tourist Expenditure (USD)")
print(f"Result for Tourist Expenditure (USD) in Australia (2018):\n{tourist_expenditure_result}\n")
# Final Task
# Subtask:
# Summarize the functionality of the new generalized function and demonstrate its ability to extract and answer questions about various numerical factors from the dataset using Qwen.

#Summary:
#Q&A
#What was the 'Unemployment rates' for 'United States' in '2019'? The Unemployment rates in the United States in 2019 were 3.7%.
#What was the 'Tourist Expenditure (USD)' for 'Australia' in '2018'? The Tourist Expenditure (USD) in Australia in 2018 was 47,259.8.
#Data Analysis Key Findings
#A new generalized function, get_factor_value_answer, was successfully implemented, replacing the previous get_unemployment_rate_answer. This function now accepts country, year, and factor_name as parameters, allowing for flexible data extraction.
#The function accurately extracted the 'Unemployment rates' for 'United States' in '2019' as '3.7' from the provided CSV data.
#It also successfully extracted the 'Tourist Expenditure (USD)' for 'Australia' in '2018' as '47,259.8' from the dataset.
#Dynamic prompts were constructed for Qwen, embedding these extracted factual values, leading to precise answers from the language model.
#Qwen's responses confirmed the extracted values, stating: "The Unemployment rates in the United States in 2019 were 3.7%." and "The Tourist Expenditure (USD) in Australia in 2018 was 47,259.8."
#Insights or Next Steps
#The get_factor_value_answer function provides a robust and flexible method for querying specific numerical factors from structured data, significantly improving the reusability and scalability of the data analysis workflow.
#Future enhancements could include error handling for cases where the specified factor_name is not found in the dataset or when data for the given country and year is missing, returning more informative messages.
